### ISSUE TITLE
Performance issue (Adventure Backpacks taking 60% on player tick)

### ISSUE THREAD

**Issue by Slind14** [runescapejon/AdventureBackpack2#10]
Hey,

currently the entire backpack data including all its contents is being sent to the client on every tick. This is a major overhead causing the backpack mod to eat up 60-80% of a servers resources when used a lot and filled up.

![](https://i.imgur.com/wW8KZ2Y.png)
![](https://i.imgur.com/jERAbVf.png)

My suggestion is to 1. only sent the required data, 2. reduce the frequency (e.g. every 20th tick).

**Comment by runescapejon** [comment]
I'll fix it asap

**Comment by runescapejon** [comment]
what program is that your using

**Comment by Slind14** [comment]
visualvm, ships with java jdk

**Comment by runescapejon** [comment]
thanks I'm going to rework this tomorrow because i'm busy with family today

**Comment by TheIcyOne** [comment]
I assume the logical solution would be to only send information on contents when the backpack is used, although I haven't dealt enough with packets to know how complex that would be.

**Comment by Slind14** [comment]
The Container API should take care of that already, no need to send it additionally unless there is some hidden reason.

**Comment by knoxz** [comment]
yes if you extend the container interface it you dont really need to do anything. Hotkey -> open container -> make gui and the container object should give you everything you need on client side already.

http://www.minecraftforge.net/wiki/Containers_and_GUIs

Here is some example code.

**Comment by knoxz** [comment]
As you are syncing for Render reasons (?), you could have the renderer on the client gather the nessesary informations when a new backpack comes in render distance and then save the data for that backpack/player.
It would only gather the information once. You either do not care if anybody is switching stuff.... or maybe Update the information every like 1000 ticks if the backpack is still in range.
That could also happen on the client side and just Request the new information if outdated.

We have a lot of players at spawn and the data that is beeing send grows exponential at the moment. ;-)

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases
try this i haven't tested it because i am very busy with other stuff

**Comment by Slind14** [comment]
is this the change?
https://github.com/runescapejon/AdventureBackpack2/commit/90c8e3ba6205a832f2795cd3165dcbeab23c4390#diff-29e1127f091460ef0512b6448ac6a5c1L52
That int is never used..

**Comment by runescapejon** [comment]
ehhh sorry not soo good at making Performance better

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb21pre

**Comment by knoxz** [comment]
We already fixed the "issue" ourselfs.
We just removed the sync funktion from every playerTick.
Tools and other stuff are only synced when the player opens the backpack but as this only effects rendering it does not really effect anything. 
If you want, we can commit the fix.

Best regards

**Comment by runescapejon** [comment]
please post the fixes on pull request please and thanks

**Comment by knoxz** [comment]
you did make an commit. Changing an as "unused" marked variable which did change anything at all and said: "Try this."
If you want to help, thats admirable and really nice of you.
BUT making commits that crash the programm or do nothing at all is not helping.
You might want to start creating a mod or two on your own to learn before you try fixing problems you do not really understand.
Thats not rude, thats just an advice. I did not want to insult anyone.

for your information in your other recent recent push you closed:
Your method is calling itself... creating a infinite loop that would crash anything trying it to run with an overflow because it never ends.

**Comment by runescapejon** [comment]
yes i understand i had made a few mods before but only little mods nothing too big

**Comment by knoxz** [comment]
this mod was definitely lot of work and is really great.
but... it has some more or less bigger flaws and the coding "style" isnt really that good.
I would not take it as a good example for some flawless code. ;-)

I nearly have my masters degree in computer science and tutor bachelor students in programming.
Even for me it would take some considerable time to understand the code and everything that is done here.
Its no small task.

**Comment by knoxz** [comment]
pushed the fix with some explanation btw

**Comment by runescapejon** [comment]
ahh okay yea you went to school to learn programming i had to take online classes for free so look in my point of view and not much has learn I'm surprise i went this far still learning and thanks to Noppes and other dev. for point me in the right direction i had learned a lot not by classes but by writing and find the mistakes and fixing them :) but anyways i seen your forked and yea i didn't notice that class file i was looking somewhere else but thanks I'm going to make an update later on today and resolve this issue I'm going to close this issue mainly because you guys already have the fixes
