### ISSUE TITLE
want a fix

### ISSUE THREAD

**Issue by hhheeexxx** [runescapejon/AdventureBackpack2#100]
I request a fix:
If backpack in hand, and it's stack of backpack (>1) then 
I offer to make it so that it does not open. 

There is another way to dup:
Make stack of backpack, then open it, put item, close it.
Then unstack backpacks, and get items back.

**Comment by Ugachaga** [comment]
At the first place: how did you manage to stack em up?
Backpacks supposed to be unstackable at all.

**Comment by hhheeexxx** [comment]
Some other mods have bugs and do stack of things that should not. And some of these mods are not supported and do not have open source for fix them. And dupers know how to use it, believe me. On our server any week come new guy and want to use dupes.

**Comment by hhheeexxx** [comment]
Favorite thing of duper is stack backpacks, then put item, then unstack, and get items back. It's work on forestry backpack, not work on backpacks mod because it's contains a link not items, work on project red backpack and on many things like that.

**Comment by Ugachaga** [comment]
Ok, so it's not an AdventureBackpack bug. 

To make decision on your request I need real examples of abandoned closed-soursed mods and its blocks/items allowing to stack unstackable. Generally, I'm against adding special cases for similar crossmod "fixes", but it may depends.

**Comment by Ugachaga** [comment]
Well, I've investigate a bit and found [this ](https://github.com/rwtema/extrautilities/issues/768) evil dupe with ExU cabinets. Fixed in the attached file, just replace original ContainerFilingCabinet.class from ExU. Is there any other sources of this dupe?

@Dream-Master might be interesting for you too.

[ExtraUtilities-1.22.13_cabinetDupeFix.gz](https://github.com/runescapejon/AdventureBackpack2/files/932301/ExtraUtilities-1.22.13_cabinetDupeFix.gz)

**Comment by hhheeexxx** [comment]
I was going to test more than ExU cabinets  and ask the knowledgeable people, but there was not time to do it yet.
@Dream-Master, you can fix that bug with ExU cabinet by ModFixNG plugin.

**Comment by Dream-Master** [comment]
@hhheeexxx 
@Ugachaga 
yes will include this in the next update.
