### ISSUE TITLE
Question: How to switch tools?

### ISSUE THREAD

**Issue by Flexico** [runescapejon/AdventureBackpack2#50]
I just updated to the latest version (f-beta-12) and shift+scroll doesn't switch my tools anymore. How do I do that now?

**Comment by CyberSpongie** [comment]
i had this problem, what i did to fix this to by messing around in the config and restart mc and it work for me

**Comment by Flexico** [comment]
What in the config did you change?

**Comment by CyberSpongie** [comment]
`Enable Tools Cycling` config option

**Comment by CyberSpongie** [comment]
oh nvm it looks like it's a bug

**Comment by Flexico** [comment]
Yeah, I have that enabled, still no work. =P

**Comment by Flexico** [comment]
Wow that was fast!

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9fb13

**Comment by Ugachaga** [comment]
You have to enable tool cycling for backpack by pressing BackpackToggleActionKey. You may disable/enable it ingame.
In beta 13 tool cycling enabled all the time.

**Comment by runescapejon** [comment]
Ohhh oop's ill revert it back, i see it now thanks

**Comment by runescapejon** [comment]
it may be enable all the time cause in the config i had to where you can disable it then restart your minecraft and i had test it that work out fine, but your way it's much better to have it enable/disable ingame instead of config tho 

Just edited the [Wiki](https://github.com/runescapejon/AdventureBackpack2/wiki) so the information is there
