### ISSUE TITLE
Small visual bug & question

### ISSUE THREAD

**Issue by Sir-Chi** [runescapejon/AdventureBackpack2#97]
firstly with the new coal jetpack, when hovering over the item looking at the recipe in NEI, the name doesn't appear. (See below)
![2017-04-16_08 59 11](https://cloud.githubusercontent.com/assets/17249849/25069769/01995b94-2283-11e7-9916-66e4d527d9f5.png)

And now for the question. With the new changes to the register method for the 2 jetpacks, when I changed my CraftTweaker script to follow the new format, it doesn't change the recipe and keeps giving errors
My script:
recipes.remove(<adventurebackpack:copterPack>.withTag({}));
The error received is Error parsing test.zs:2 -- ) expected

Any help is appreciated and thanks for keeping a great mod going.

**Comment by Ugachaga** [comment]
"Unnamed" in NEI signals that NBT not setting up correctly.

As for MineTweaker configuration, I'm not very experienced with that. It seems MT cannot handle empty tags (or you have to use special syntax, dunno), so every tag have to had atlest one element: `.withTag({fuelTank: {Empty: ""}})` instead of just `.withTag({}))` will work. See [here ](https://github.com/GTNewHorizons/NewHorizons/pull/1282/files#diff-9d3c5ca9a53fd0271edd05e985af90d8L168) for example.

**Comment by Sir-Chi** [comment]
Thank you very much this did the trick!  You've been a great help thanks.
And thanks again for helping keep this mod going <3
